# Action   Protocol   IP_Address       Port   Direction
DROP       TCP        192.168.1.100    80     OUT
DROP       ANY        192.168.1.100    ANY    IN
DROP       TCP        ANY              22     IN
ACCEPT     ANY        ANY              ANY    ANY
